#!/usr/bin/env python3
"""Manage discovery-cycle projects (list, inspect, delete).

A *project* is identified by a run-id (`<8-lowercase-alphanumeric>-<MMDDYY>`,
generated by `scripts/gen_run_id.py`) and encompasses everything keyed by that
run-id across the workspace:

  - ideas/<run-id>/<slug>.md            (active idea cards)
  - ideas/killed/<run-id>/<slug>.md     (killed cards from this cycle)
  - market-research/<run-id>/*          (triage, scan, trends, validations, scopings)

For each slug found in those folders, additionally:

  - web-apps/<slug>/**                  (if scoped to a web app)
  - mobile-apps/<slug>/**               (if scoped to a mobile app)
  - generated/**/*<slug>*               (exported PDFs/DOCXs referencing the slug)

USAGE
    python3 scripts/projects.py list [--json]
    python3 scripts/projects.py show <run-id> [--json]
    python3 scripts/projects.py delete <run-id> --force

The `delete` subcommand requires `--force` as a safety guard. The intended
interactive flow is through `/projects`, which handles the
multi-step user confirmations before invoking `delete --force`. Direct CLI
use is supported for scripted workflows.
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUN_ID_RE = re.compile(r"^[a-z0-9]{8}-\d{6}$")


def discover_run_ids() -> list[str]:
    """Find every unique run-id present anywhere in the workspace."""
    ids: set[str] = set()
    for base in (
        ROOT / "ideas",
        ROOT / "ideas" / "killed",
        ROOT / "market-research",
    ):
        if not base.exists():
            continue
        for child in base.iterdir():
            if child.is_dir() and RUN_ID_RE.match(child.name):
                ids.add(child.name)
    return sorted(ids)


def slugs_for_run(run_id: str) -> set[str]:
    """Return every slug associated with this run-id, drawn from card filenames
    and from validation-/scoping- prefixed market-research files."""
    slugs: set[str] = set()
    for cards_dir in (ROOT / "ideas" / run_id, ROOT / "ideas" / "killed" / run_id):
        if cards_dir.exists():
            for md in cards_dir.glob("*.md"):
                slugs.add(md.stem)
    mr = ROOT / "market-research" / run_id
    if mr.exists():
        for md in mr.glob("validation-*.md"):
            slugs.add(md.stem[len("validation-") :])
        for md in mr.glob("scoping-*.md"):
            slugs.add(md.stem[len("scoping-") :])
    return slugs


def artifacts_for_project(run_id: str) -> dict[str, list[Path]]:
    """Return all on-disk artifacts for the given run-id, grouped by category."""
    result: dict[str, list[Path]] = {
        "ideas": [],
        "killed_ideas": [],
        "market_research": [],
        "web_apps": [],
        "mobile_apps": [],
        "generated": [],
    }

    ideas_dir = ROOT / "ideas" / run_id
    if ideas_dir.exists():
        result["ideas"].append(ideas_dir)

    killed_dir = ROOT / "ideas" / "killed" / run_id
    if killed_dir.exists():
        result["killed_ideas"].append(killed_dir)

    mr_dir = ROOT / "market-research" / run_id
    if mr_dir.exists():
        result["market_research"].append(mr_dir)

    slugs = slugs_for_run(run_id)
    for slug in sorted(slugs):
        wa = ROOT / "web-apps" / slug
        if wa.exists():
            result["web_apps"].append(wa)
        ma = ROOT / "mobile-apps" / slug
        if ma.exists():
            result["mobile_apps"].append(ma)
        gen = ROOT / "generated"
        if gen.exists():
            for f in gen.rglob(f"*{slug}*"):
                if f.is_file():
                    result["generated"].append(f)

    return result


def count_files(artifacts: dict[str, list[Path]]) -> int:
    n = 0
    for paths in artifacts.values():
        for p in paths:
            if p.is_file():
                n += 1
            elif p.is_dir():
                n += sum(1 for _ in p.rglob("*") if _.is_file())
    return n


def project_summary(run_id: str) -> dict:
    """Lightweight stats for the list view."""
    slugs = slugs_for_run(run_id)
    ideas_dir = ROOT / "ideas" / run_id
    killed_dir = ROOT / "ideas" / "killed" / run_id
    mr_dir = ROOT / "market-research" / run_id

    n_cards = len(list(ideas_dir.glob("*.md"))) if ideas_dir.exists() else 0
    n_killed = len(list(killed_dir.glob("*.md"))) if killed_dir.exists() else 0
    n_validations = len(list(mr_dir.glob("validation-*.md"))) if mr_dir.exists() else 0
    n_scopings = len(list(mr_dir.glob("scoping-*.md"))) if mr_dir.exists() else 0
    has_scan = (mr_dir / "scan.md").exists() if mr_dir.exists() else False
    has_trends = (mr_dir / "trends.md").exists() if mr_dir.exists() else False
    n_web_apps = sum(1 for s in slugs if (ROOT / "web-apps" / s).exists())
    n_mobile_apps = sum(1 for s in slugs if (ROOT / "mobile-apps" / s).exists())

    date_part = run_id.split("-", 1)[1]
    mm, dd, yy = date_part[:2], date_part[2:4], date_part[4:6]
    date_str = f"20{yy}-{mm}-{dd}"

    return {
        "run_id": run_id,
        "date": date_str,
        "active_cards": n_cards,
        "killed_cards": n_killed,
        "validations": n_validations,
        "scopings": n_scopings,
        "has_scan": has_scan,
        "has_trends": has_trends,
        "web_apps": n_web_apps,
        "mobile_apps": n_mobile_apps,
        "total_slugs": len(slugs),
    }


def summary_line(s: dict) -> str:
    parts = [f"{s['active_cards']} card(s)"]
    if s["killed_cards"]:
        parts.append(f"{s['killed_cards']} killed")
    parts.append(f"{s['validations']} validation(s)")
    if s["scopings"]:
        parts.append(f"{s['scopings']} scoping(s)")
    if s["has_scan"]:
        parts.append("scan")
    if s["has_trends"]:
        parts.append("trends")
    if s["web_apps"]:
        parts.append(f"{s['web_apps']} web-app(s)")
    if s["mobile_apps"]:
        parts.append(f"{s['mobile_apps']} mobile-app(s)")
    return f"{s['run_id']} ({s['date']}) — {', '.join(parts)}"


def cmd_list(args) -> int:
    run_ids = discover_run_ids()
    if not run_ids:
        if args.json:
            print(json.dumps([]))
        else:
            print("No projects found in this workspace.")
        return 0
    summaries = [project_summary(rid) for rid in run_ids]
    if args.json:
        print(json.dumps(summaries, indent=2))
        return 0
    print(f"Found {len(run_ids)} project(s):\n")
    for s in summaries:
        print(f"  {summary_line(s)}")
    return 0


def cmd_show(args) -> int:
    run_id = args.run_id
    if not RUN_ID_RE.match(run_id):
        print(f"ERROR: invalid run-id format: {run_id}", file=sys.stderr)
        return 2
    artifacts = artifacts_for_project(run_id)
    if not any(artifacts.values()):
        if args.json:
            print(json.dumps({"run_id": run_id, "artifacts": {}, "total_files": 0}))
        else:
            print(f"No artifacts found for run-id {run_id}.")
        return 1

    if args.json:
        out = {
            "run_id": run_id,
            "artifacts": {
                cat: [str(p.relative_to(ROOT)) for p in paths]
                for cat, paths in artifacts.items()
                if paths
            },
            "total_files": count_files(artifacts),
        }
        print(json.dumps(out, indent=2))
        return 0

    print(f"Artifacts for project {run_id}:\n")
    for category, paths in artifacts.items():
        if not paths:
            continue
        label = category.replace("_", " ")
        print(f"  [{label}]")
        for p in paths:
            rel = p.relative_to(ROOT)
            if p.is_dir():
                files = sorted(f for f in p.rglob("*") if f.is_file())
                print(f"    {rel}/ ({len(files)} file(s))")
                for f in files[:10]:
                    print(f"      └── {f.relative_to(p)}")
                if len(files) > 10:
                    print(f"      └── ... and {len(files) - 10} more")
            else:
                print(f"    {rel}")
    print(f"\nTotal files: {count_files(artifacts)}")
    return 0


def cmd_delete(args) -> int:
    run_id = args.run_id
    if not RUN_ID_RE.match(run_id):
        print(f"ERROR: invalid run-id format: {run_id}", file=sys.stderr)
        return 2
    if not args.force:
        print(
            "ERROR: --force flag required to actually delete.\n"
            "       This is a safety guard — the deletion is irreversible.\n"
            "       Use `/projects` for the interactive flow with\n"
            "       multi-step confirmations.",
            file=sys.stderr,
        )
        return 2

    artifacts = artifacts_for_project(run_id)
    if not any(artifacts.values()):
        print(f"No artifacts found for run-id {run_id}.")
        return 1

    total = count_files(artifacts)
    for paths in artifacts.values():
        for p in paths:
            if p.is_dir():
                shutil.rmtree(p)
            elif p.is_file():
                p.unlink()

    print(f"Deleted project {run_id}: {total} file(s) removed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Manage discovery-cycle projects in the workspace."
    )
    sub = parser.add_subparsers(dest="action", required=True)

    list_p = sub.add_parser("list", help="List all projects with a one-line summary each.")
    list_p.add_argument("--json", action="store_true", help="Output as JSON.")
    list_p.set_defaults(func=cmd_list)

    show_p = sub.add_parser(
        "show", help="Show all artifacts that would be deleted for a project (dry-run)."
    )
    show_p.add_argument("run_id")
    show_p.add_argument("--json", action="store_true", help="Output as JSON.")
    show_p.set_defaults(func=cmd_show)

    del_p = sub.add_parser(
        "delete", help="Permanently delete a project's artifacts. Requires --force."
    )
    del_p.add_argument("run_id")
    del_p.add_argument(
        "--force",
        action="store_true",
        help="Required safety flag — without it, the command refuses.",
    )
    del_p.set_defaults(func=cmd_delete)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
